name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 'lts/*'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - name: Test on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y xsel xvfb
          Xvfb :99 &
          export DISPLAY=:99
          pnpm test
      - name: Test on other OS
        if: matrix.os != 'ubuntu-latest'
        run: |
          pnpm test

